# Generated by Django 4.2.11 on 2024-06-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
