# Generated by Django 4.2.11 on 2024-06-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_delete_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='area_code',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='country_english',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='district',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='isp',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='province',
        ),
    ]
