# Generated by Django 4.2.11 on 2024-04-15 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('table_name', models.CharField(default='未关联表', help_text='操作表名', max_length=32, verbose_name='表名')),
                ('operate_obj', models.CharField(default='未关联对象', help_text='操作对象', max_length=32, verbose_name='操作对象')),
                ('operate_des', models.CharField(default='未有操作详情', help_text='操作详情', max_length=1024, verbose_name='操作详情')),
                ('user', models.ForeignKey(db_constraint=False, help_text='操作人员', on_delete=django.db.models.deletion.CASCADE, related_name='ruser', related_query_name='quser', to=settings.AUTH_USER_MODEL, verbose_name='操作人员')),
            ],
            options={
                'verbose_name': '用户操作日志表',
                'verbose_name_plural': '用户操作日志表',
                'db_table': 'operation_log',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
