# Generated by Django 4.2.11 on 2024-04-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_operationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlog',
            name='update_datetime',
        ),
    ]
