# Generated by Django 4.2.11 on 2024-04-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_operationlog_update_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlog',
            name='table_name',
        ),
    ]
