# Generated by Django 4.2.11 on 2024-04-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_operationlog_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='操作人员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruser', related_query_name='quser', to=settings.AUTH_USER_MODEL, verbose_name='操作人员'),
        ),
    ]
