# Generated by Django 4.2.11 on 2024-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='accountId',
            field=models.CharField(blank=True, default='1', help_text='用户标识', max_length=255, null=True, verbose_name='用户标识'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, default='18888888888', help_text='电话', max_length=255, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, default='user', help_text='角色', max_length=64, null=True, verbose_name='角色'),
        ),
    ]
