# Generated by Django 4.2.11 on 2024-06-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0009_ogroup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OGroup',
            new_name='Department',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '组别', 'verbose_name_plural': '组别组'},
        ),
    ]
