# Generated by Django 4.2.11 on 2024-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_ogroup_department_alter_department_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, to='user.department'),
        ),
    ]
