# Generated by Django 4.2.9 on 2024-02-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_contact_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dut',
            name='ref',
            field=models.CharField(blank=True, help_text='文档编号', max_length=32, null=True, verbose_name='文档编号'),
        ),
    ]
