# Generated by Django 4.2.9 on 2024-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_dut_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dut',
            name='release_date',
            field=models.DateField(auto_now_add=True, help_text='发布时间', null=True, verbose_name='发布时间'),
        ),
    ]
