# Generated by Django 4.2.9 on 2024-02-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_alter_dut_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abbreviation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='缩略语', max_length=64, verbose_name='缩略语')),
                ('des', models.CharField(help_text='描述', max_length=256, verbose_name='描述')),
            ],
            options={
                'verbose_name': '缩略语和行业词汇',
                'verbose_name_plural': '缩略语和行业词汇',
                'db_table': 'project_abbreviation',
            },
        ),
    ]
