# Generated by Django 4.2.9 on 2024-03-01 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdemand',
            name='otherDesign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odField', related_query_name='odQuery', to='project.design'),
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='design',
            field=models.ForeignKey(db_constraint=False, help_text='归属设计需求', on_delete=django.db.models.deletion.CASCADE, related_name='dtField', related_query_name='dtQuery', to='project.design', verbose_name='归属设计需求'),
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='dut',
            field=models.ForeignKey(db_constraint=False, help_text='归属被测件', on_delete=django.db.models.deletion.CASCADE, related_name='dutField', related_query_name='dtQuery', to='project.dut', verbose_name='归属被测件'),
        ),
    ]
