# Generated by Django 4.2.9 on 2024-03-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_testdemand_otherdesign_alter_testdemand_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdemand',
            name='otherDesign',
        ),
        migrations.AddField(
            model_name='testdemand',
            name='otherDesign',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, related_name='odField', related_query_name='odQuery', to='project.design'),
        ),
    ]
