# Generated by Django 4.2.9 on 2024-03-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_testdemand_otherdesign_testdemand_otherdesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='case',
        ),
        migrations.AddField(
            model_name='problem',
            name='case',
            field=models.ManyToManyField(db_constraint=False, help_text='归属测试用例-多对多', related_name='caseField', related_query_name='caseQuery', to='project.case', verbose_name='归属测试用例'),
        ),
    ]
