# Generated by Django 4.2.9 on 2024-03-13 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_case_isleaf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('id',), 'verbose_name': '问题单', 'verbose_name_plural': '问题单'},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='design',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='dut',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='isLeaf',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='key',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='round',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='title',
        ),
    ]
