# Generated by Django 4.2.9 on 2024-03-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_problem_options_remove_problem_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='project',
            field=models.ForeignKey(db_constraint=False, default=6, help_text='归属项目', on_delete=django.db.models.deletion.CASCADE, related_name='projField', related_query_name='projQuery', to='project.project', verbose_name='归属项目'),
            preserve_default=False,
        ),
    ]
