# Generated by Django 4.2.11 on 2024-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_problem_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='soft_type',
            field=models.SmallIntegerField(choices=[(1, '新研'), (2, '改造')], default=1, verbose_name='软件类型'),
        ),
    ]
