# Generated by Django 4.2.11 on 2024-03-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_project_soft_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='devplant',
            field=models.CharField(blank=True, help_text='开发环境', max_length=128, null=True, verbose_name='开发环境'),
        ),
        migrations.AddField(
            model_name='project',
            name='runtime',
            field=models.CharField(blank=True, help_text='运行环境', max_length=128, null=True, verbose_name='运行环境'),
        ),
    ]
