# Generated by Django 4.2.11 on 2024-03-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_project_devplant_project_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='devplant',
            field=models.CharField(blank=True, help_text='开发环境', max_length=8, null=True, verbose_name='开发环境'),
        ),
        migrations.AlterField(
            model_name='project',
            name='runtime',
            field=models.CharField(blank=True, help_text='运行环境', max_length=8, null=True, verbose_name='运行环境'),
        ),
    ]
