# Generated by Django 4.2.11 on 2024-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_alter_project_devplant_alter_project_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solve',
            field=models.TextField(blank=True, help_text='问题处理方式，该字段需要关联“status=1”', null=True, verbose_name='问题处理方式'),
        ),
    ]
