# Generated by Django 4.2.11 on 2024-04-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_problem_solve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dut',
            name='comment_line',
        ),
        migrations.RemoveField(
            model_name='dut',
            name='total_code_line',
        ),
        migrations.RemoveField(
            model_name='dut',
            name='total_line',
        ),
        migrations.AlterField(
            model_name='dut',
            name='pure_code_line',
            field=models.CharField(blank=True, help_text='纯代码行数', max_length=64, null=True, verbose_name='纯代码行数'),
        ),
        migrations.AlterField(
            model_name='dut',
            name='total_comment_line',
            field=models.CharField(blank=True, help_text='纯注释行', max_length=64, null=True, verbose_name='纯注释行'),
        ),
    ]
