# Generated by Django 4.2.11 on 2024-05-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_rename_pure_code_line_dut_code_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdemand',
            name='premise',
        ),
        migrations.RemoveField(
            model_name='testdemand',
            name='termination',
        ),
    ]
