# Generated by Django 4.2.11 on 2024-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_remove_testdemand_premise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdemandcontent',
            name='testXuQiu',
        ),
        migrations.RemoveField(
            model_name='testdemandcontent',
            name='testYuQi',
        ),
        migrations.AddField(
            model_name='testdemandcontent',
            name='condition',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试子项具体条件'),
        ),
        migrations.AddField(
            model_name='testdemandcontent',
            name='expect',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='期望'),
        ),
        migrations.AddField(
            model_name='testdemandcontent',
            name='observe',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试子项观察'),
        ),
        migrations.AddField(
            model_name='testdemandcontent',
            name='operation',
            field=models.CharField(blank=True, max_length=3072, null=True, verbose_name='测试子项操作'),
        ),
        migrations.AddField(
            model_name='testdemandcontent',
            name='subDesc',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试子项描述-对应表格测试项描述'),
        ),
        migrations.AddField(
            model_name='testdemandcontent',
            name='subName',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试子项名称'),
        ),
    ]
