# Generated by Django 4.2.11 on 2024-05-14 16:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_remove_testdemandcontent_testxuqiu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='expect',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='revokeDate',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='revokePerson',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='suggest',
        ),
        migrations.AddField(
            model_name='problem',
            name='analysis',
            field=tinymce.models.HTMLField(blank=True, help_text='开发人员填写-原因分析', null=True, verbose_name='开发人员填写-原因分析'),
        ),
        migrations.AddField(
            model_name='problem',
            name='effect_scope',
            field=tinymce.models.HTMLField(blank=True, help_text='开发人员填写-影响域分析', null=True, verbose_name='开发人员填写-影响域分析'),
        ),
        migrations.AddField(
            model_name='problem',
            name='verify_result',
            field=tinymce.models.HTMLField(blank=True, help_text='问题描述', null=True, verbose_name='问题描述'),
        ),
        migrations.AlterField(
            model_name='case',
            name='initialization',
            field=models.CharField(blank=True, help_text='初始化条件', max_length=128, null=True, verbose_name='初始条件'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='designerPerson',
            field=models.CharField(blank=True, help_text='开发人员', max_length=16, null=True, verbose_name='开发人员'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='operation',
            field=tinymce.models.HTMLField(blank=True, help_text='问题描述', null=True, verbose_name='问题描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='result',
            field=tinymce.models.HTMLField(blank=True, help_text='问题结果/影响', null=True, verbose_name='问题结果/影响'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solve',
            field=models.TextField(blank=True, help_text='开发人员填写-改正措施，该字段需要关联“status=1”', null=True, verbose_name='开发人员填写-改正措施'),
        ),
    ]
