# Generated by Django 4.2.11 on 2024-05-31 16:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_remove_problem_expect_remove_problem_revokedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='exe_time',
            field=models.DateField(blank=True, help_text='执行时间', null=True, verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='design',
            name='round',
            field=models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='dsField', related_query_name='rsQuery', to='project.round', verbose_name='归属轮次'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='verify_result',
            field=tinymce.models.HTMLField(blank=True, help_text='回归结果', null=True, verbose_name='回归结果'),
        ),
    ]
