# Generated by Django 4.2.11 on 2024-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_case_exe_time_alter_design_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='location',
            field=models.CharField(default=1, help_text='测评执行地点', max_length=30, verbose_name='测评执行地点'),
            preserve_default=False,
        ),
    ]
