# Generated by Django 4.2.11 on 2024-06-17 10:14

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_alter_project_soft_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='closeMethod',
            field=models.JSONField(blank=True, default=apps.project.models.create_list_1, help_text='闭环方式', null=True, verbose_name='闭环方式'),
        ),
        migrations.AlterField(
            model_name='project',
            name='abbreviation',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='缩略语', null=True, verbose_name='缩略语'),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='被测语言', null=True, verbose_name='被测语言'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='项目成员', null=True, verbose_name='项目成员'),
        ),
        migrations.AlterField(
            model_name='project',
            name='plant_type',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='平台类型', null=True, verbose_name='平台类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='standard',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='依据标准', null=True, verbose_name='依据标准'),
        ),
        migrations.AlterField(
            model_name='project',
            name='test_level',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='测试级别', null=True, verbose_name='测试级别'),
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='otherDesign',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='odField', related_query_name='odQuery', to='project.design'),
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='testMethod',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='测试方法', verbose_name='测试方法'),
        ),
    ]
